### ISSUE TITLE
Touchscreen UI Visuals

### ISSUE THREAD

**Issue by jayportimo** [AWAP-6/backend#2]
## Task list:

- [ ] Code display/box
- [ ] Keypad (numbers from 0 to 9)
- [ ] Enter button
- [ ] Header and other relevant information text
- [ ] Some way (dropdown menu?) to choose which parcel locker location (1-5) is being accessed
